name: generatooorr
author: valory
version: 0.1.0
description: A service for generating shorts (AI generated short films).
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeihoplqp3y2k6y4anmmtw4jfnvxuul36hurubnn2mdyxyuoaewibaa
fingerprint_ignore_patterns: []
agent: valory/generatooorr:0.1.0:bafybeibs7lylcgcn4olmjibfnldwo7lm47c57ruzrwmzpp3gtzcs37ud3q
number_of_agents: 1
deployment:
  agent:
    ports:
      0:
        8000: 8000
---
public_id: valory/generatooorr_abci:0.1.0
type: skill
0:
  models:
    params:
      args:
        setup:
          all_participants: ${ALL_PARTICIPANTS:list:["0xE4B3a17f8159B1eB42864DdbA6a438432Bc10709"]}
          safe_contract_address: ${SAFE_CONTRACT_ADDRESS:str:0xef5B17d62671ef9682Be66D5b81c2001B3c71fAC}
          consensus_threshold: ${CONSENSUS_THRESHOLD:int:null}
        blockchain_shorts_contract: ${BLOCKCHAIN_SHORTS_CONTRACT:str:0x8F2D3E5bfc2e51C553733E9AEb7aeC4454272442}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        tendermint_com_url: ${TENDERMINT_COM_URL:str:http://localhost:8080}
        tendermint_url: ${TENDERMINT_URL:str:http://localhost:26657}
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_0:str:node0:26656}
        termination_sleep: ${TERMINATION_SLEEP:int:900}
        termination_from_block: ${TERMINATION_FROM_BLOCK:int:0}
        use_termination: ${USE_TERMINATION:bool:false}
        mech_agent_address: ${AGENT_MECH_CONTRACT_ADDRESS:str:0x37C484cc34408d0F827DB4d7B6e54b8837Bf8BDA}
        reset_period_count: ${RESET_PERIOD_COUNT:int:1000}
        use_slashing: ${USE_SLASHING:bool:false}
        slash_cooldown_hours: ${SLASH_COOLDOWN_HOURS:int:3}
        slash_threshold_amount: ${SLASH_THRESHOLD_AMOUNT:int:10000000000000000}
        light_slash_unit_amount: ${LIGHT_SLASH_UNIT_AMOUNT:int:5000000000000000}
        serious_slash_unit_amount: ${SERIOUS_SLASH_UNIT_AMOUNT:int:8000000000000000}
        agent_registry_address: ${AGENT_REGISTRY_ADDRESS:str:0x84B4DA67B37B1EA1dea9c7044042C1d2297b80a0}
        agent_id: ${AGENT_ID:int:1}
        reset_tendermint_after: ${RESET_TENDERMINT_AFTER:int:50}
        w3_inbox_project_id: ${PROJECT_ID:str:w3_inbox_project_id}
        w3_notification_type: ${NOTIFICATION_TYPE:str:w3_notification_type}
        w3_notification_api_key: ${NOTIFICATION_API_KEY:str:w3_notification_api_key}
        inbox_auth: ${INBOX_AUTH:str:inbox_auth}
        farcaster_auth: ${FARCASTER_AUTH:str:farcaster_auth}
---
public_id: valory/ledger:0.19.0
type: connection
0:
  config:
    ledger_apis:
      ethereum:
        address: ${ETHEREUM_RPC_0:str:http://host.docker.internal:8545}
        chain_id: 1
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${ACN_URI:str:acn.staging.autonolas.tech:9005}
    public_key: ${ACN_NODE_PUBLIC_KEY:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${ACN_NODE_PUBLIC_KEY:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_11000.txt
is_abstract: false
---
public_id: valory/http_server:0.22.0:bafybeicblltx7ha3ulthg7bzfccuqqyjmihhrvfeztlgrlcoxhr7kf6nbq
type: connection
0:
  config:
    port: ${HTTP_INGRESS_PORT:int:8000}
---
public_id: valory/farcaster:0.1.0:bafybeihrixgptxuqpf2s4nujypwlv5aed2nboozq5kl4c26cxw6r7si2x4
type: connection
0:
  config:
    farcaster_mnemonic: ${FARCASTER_MNEMONIC:str:null}
